version: '3'

services:
    front:
        build:
            dockerfile: ./docker/front/Dockerfile
            context: ./
        ports:
            - "127.0.0.1:47300:80"
            - "127.0.0.1:47301:443"
        volumes:
            - ./docker/front/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/front/ssl.crt:/etc/nginx/ssl.crt
            - ./docker/front/ssl.key:/etc/nginx/ssl.key
            - ./src:/home/docker
        labels:
            - "traefik.frontend.rule=Host:magento.local"
            - "traefik.port=443"
            - "traefik.protocol=https"
        networks: { default: { aliases: ['magento.local']}}
        depends_on: ["engine"]
        working_dir: /etc/nginx

    engine:
        build: 
            dockerfile: ./docker/engine/Dockerfile
            context: ./
        user: "1000"
        environment:
            - "COMPOSER_HOME=/usr/local/bin"
        ports:
            - "127.0.0.1:47303:9000"
        volumes:
            - ./docker/engine/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro
            - ./docker/front/ssl.crt:/etc/nginx/ssl.crt
            - ./docker/front/ssl.key:/etc/nginx/ssl.key
            - ./src:/home/docker
            - ./src/auth.json:/usr/local/bin/auth.json
        depends_on: ["db"]

    db:
        image: mysql:5.7
        ports:
            - "127.0.0.1:47304:3306"
        volumes:
            - db_data:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=root"
            - "MYSQL_DATABASE=magento"
            - "MYSQL_USER=magento"
            - "MYSQL_PASSWORD=magento"

    cache:
        image: redis:alpine
        ports:
            - 127.0.0.1:47310:6379

    fpc:
        image: redis:alpine
        ports:
            - 127.0.0.1:47311:6379

    session:
        image: redis:alpine
        ports:
            - 127.0.0.1:47312:6379

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports: 
            - "127.0.0.1:47350:80"
        environment:
            - "MYSQL_ROOT_PASSWORD=root"
            - "MYSQL_USER=magento"
            - "MYSQL_PASSWORD=magento"
            - "PMA_HOST=db"
            - "PMA_PORT=3306"
            - "PMA_ABSOLUTE_URI=http://db.magento.local/"
            - "PMA_USER=magento"
            - "PMA_PASSWORD=magento"
        labels: 
            - "traefik.frontend.rule=Host:db.magento.local"
            - "traefik.port=80"
        networks: { default: { aliases: ['db.magento.local']}}
        depends_on: ["db"]

volumes:
    db_data:
        driver: "local"